### ISSUE TITLE
Tracking issue: add React components for Penumbra action views

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra_dapp#18]
In #16 I added react components for spend and action views, replacing the existing string concatenation code. The other actions are filled in with a default "unknown action" component. This should be extended to have components for all of the other Penumbra transaction actions:

Here's a list of the components that still need to be implemented, roughly in priority order:

- [x] `SpendViewComponent`
- [x] `OutputViewComponent`

### DEX

- [x] `SwapViewComponent` for `dex.v1alpha1.SwapView`
- [ ] `SwapClaimViewComponent` for `dex.v1alpha1.SwapClaimView`
- [x] `PositionOpenComponent` for `dex.v1alpha1.PositionOpen`
- [ ] `PositionCloseComponent` for `dex.v1alpha1.PositionClose`
- [ ] `PositionWithdrawComponent` for `dex.v1alpha1.PositionWithdraw`
- [ ] `PositionRewardClaimComponent` for `dex.v1alpha1.PositionRewardClaim`

For now, we can skip reward claims.

In `pcli`, we have logic to interpret Penumbra LP positions as limit orders. We will port this logic to typescript for use in position rendering in #19.

### Staking

- [ ] `DelegateComponent` for `stake.v1alpha1.Delegate`
- [ ] `UndelegateComponent` for `stake.v1alpha1.Undelegate`
- [ ] `UndelegateClaimComponent` for `stake.v1alpha1.UndelegateClaim`
- [ ] `ValidatorDefinitionComponent` for `stake.v1alpha1.ValidatorDefinition`

This is necessary to implement staking.

### IBC

- [ ] `IbcActionComponent` for `ibc.v1alpha1.IbcAction`
- [ ] `Ics20WithdrawalComponent` for `ibc.v1alpha1.Ics20Withdrawal`

To start, rather than trying to implement rendering of all of the different IBC actions that can be bundled in an `IbcAction`, we should just render the proto `Any` type (for use in inspection / debugging of IBC functionality).

### Governance

- [ ] `ProposalSubmitComponent` for `governance.v1alpha1.ProposalSubmit`
- [ ] `ProposalWithdrawComponent` for `governance.v1alpha1.ProposalWithdraw`
- [ ] `ValidatorVoteComponent` for `governance.v1alpha1.ValidatorVote`
- [ ] `DelegatorVoteViewComponent` for `DelegatorVoteView`
- [ ] `ProposalDepositClaimComponent` for `governance.v1alpha1.ProposalDepositClaim`
- [ ] `DaoSpendComponent` for `governance.v1alpha1.DaoSpend`
- [ ] `DaoOutputComponent` for `governance.v1alpha1.DaoOutput`
- [ ] `DaoDepositComponent` for `governance.v1alpha1.DaoDeposit`

These are relatively less important than the other actions.
